/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mh.gui;

import com.mh.biz.Helado;
import com.mh.biz.MaquinaHelados;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class ExecGUI extends javax.swing.JFrame {

    /**
     * Creates new form ExecGUI
     */
    public ExecGUI() {
        initComponents();
        setTitle("Maquina De Helados");
        this.setLocationRelativeTo(null);
        refrescarTabla();
        setSize(500, 600);
        setResizable(false);
        try {
            this.imagen.setSize(500, 1200);
            jPanel1.setLayout(new BorderLayout());
            this.imagen.setSize(this.imagen.getWidth(), this.imagen.getHeight());
            jPanel1.add(this.imagen, BorderLayout.CENTER);
            getContentPane().add(jPanel1, BorderLayout.CENTER);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            reproducirSonidoAlerta();
        }
        reproducirMusicaAmbiental();
    }

    private Clip clip;

    private void reproducirSonidoBoton() {
        try (InputStream inputStream = getClass().getResourceAsStream("/com/mh/sounds/botonSound.wav");) {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(inputStream);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();;
        } catch (Exception e) {
        }
    }

    private void reproducirMusicaAmbiental() {
        try (InputStream inputStream = getClass().getResourceAsStream("/com/mh/sounds/musicaAmbiental.wav");) {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(inputStream);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();;
        } catch (Exception e) {
        }
    }

    private void reproducirSonidoCompra() {
        try (InputStream inputStream = getClass().getResourceAsStream("/com/mh/sounds/buySound.wav");) {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(inputStream);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();;
        } catch (Exception e) {
        }
    }

    private void reproducirSonidoAlerta() {
        try (InputStream inputStream = getClass().getResourceAsStream("/com/mh/sounds/alertSound.wav");) {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(inputStream);
            clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();;
        } catch (Exception e) {
        }
    }

    public void refrescarTabla() {
        ArrayList<Helado> al = mh.toList();
        DefaultTableModel m = (DefaultTableModel) this.heladosTable.getModel();
        m.setNumRows(0);
        for (Helado h : al) {
            Object[] o = {h.getPosicion(), h.getNombre(), String.format("%.02f€",h.getPrecio()), h.getTipo(), h.getCantidad()};
            m.addRow(o);
        }
    }

    MaquinaHelados mh = new MaquinaHelados();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        heladosTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tresButton = new javax.swing.JButton();
        unoButton = new javax.swing.JButton();
        dosButton = new javax.swing.JButton();
        cuatroButton = new javax.swing.JButton();
        cincoButton = new javax.swing.JButton();
        seisButton = new javax.swing.JButton();
        sieteButton = new javax.swing.JButton();
        ochoButton = new javax.swing.JButton();
        nueveButton = new javax.swing.JButton();
        ceroButton = new javax.swing.JButton();
        posicionTextField = new javax.swing.JTextField();
        borrarButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pedirButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dineroTextField = new javax.swing.JTextField();
        imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        verVentasMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        heladosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición", "Sabor", "Precio", "Tipo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        heladosTable.setDragEnabled(true);
        heladosTable.setEnabled(false);
        heladosTable.getTableHeader().setReorderingAllowed(false);
        heladosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heladosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(heladosTable);
        if (heladosTable.getColumnModel().getColumnCount() > 0) {
            heladosTable.getColumnModel().getColumn(0).setResizable(false);
            heladosTable.getColumnModel().getColumn(1).setResizable(false);
            heladosTable.getColumnModel().getColumn(2).setResizable(false);
            heladosTable.getColumnModel().getColumn(3).setResizable(false);
            heladosTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        tresButton.setText("3");
        tresButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresButtonActionPerformed(evt);
            }
        });

        unoButton.setText("1");
        unoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        unoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoButtonActionPerformed(evt);
            }
        });

        dosButton.setText("2");
        dosButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosButtonActionPerformed(evt);
            }
        });

        cuatroButton.setText("4");
        cuatroButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cuatroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroButtonActionPerformed(evt);
            }
        });

        cincoButton.setText("5");
        cincoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cincoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoButtonActionPerformed(evt);
            }
        });

        seisButton.setText("6");
        seisButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        seisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisButtonActionPerformed(evt);
            }
        });

        sieteButton.setText("7");
        sieteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sieteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteButtonActionPerformed(evt);
            }
        });

        ochoButton.setText("8");
        ochoButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ochoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoButtonActionPerformed(evt);
            }
        });

        nueveButton.setText("9");
        nueveButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nueveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveButtonActionPerformed(evt);
            }
        });

        ceroButton.setText("0");
        ceroButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ceroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroButtonActionPerformed(evt);
            }
        });

        posicionTextField.setEditable(false);
        posicionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionTextFieldActionPerformed(evt);
            }
        });

        borrarButton.setText("<");
        borrarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        borrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(posicionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sieteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ceroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ochoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nueveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(unoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(unoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sieteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ochoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nueveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ceroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));

        pedirButton.setText("Pedir Helado");
        pedirButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pedirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Introducir dinero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dineroTextField.setEditable(false);
        dineroTextField.setText("0.00 €");
        dineroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pedirButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dineroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pedirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dineroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mh/img/fondoN.jpg"))); // NOI18N
        imagen.setPreferredSize(new java.awt.Dimension(100, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 124, Short.MAX_VALUE))))
        );

        verVentasMenu.setText("Menú");

        jMenuItem2.setText("Ver Ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        verVentasMenu.add(jMenuItem2);

        jMenuBar1.add(verVentasMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cincoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "5");
        }
    }//GEN-LAST:event_cincoButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        AuxIntroDinero auxIntroDinero = new AuxIntroDinero(this, true);
        auxIntroDinero.setVisible(true);
        this.dineroTextField.setText(String.valueOf(auxIntroDinero.padre.mh.getMonedero()) + " €");
        if (this.dineroTextField.getText().length() < 6) {
            this.dineroTextField.setText(String.format(auxIntroDinero.padre.mh.getMonedero() + "%s", "0 €"));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void unoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "1");
        }
    }//GEN-LAST:event_unoButtonActionPerformed

    private void cuatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "4");
        }
    }//GEN-LAST:event_cuatroButtonActionPerformed

    private void ochoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "8");
        }
    }//GEN-LAST:event_ochoButtonActionPerformed

    private void ceroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "0");
        }
    }//GEN-LAST:event_ceroButtonActionPerformed

    private void borrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        String borrado = "";
        for (int i = 0; i < this.posicionTextField.getText().length() - 1; i++) {
            borrado += this.posicionTextField.getText().charAt(i);
        }
        this.posicionTextField.setText(borrado);

    }//GEN-LAST:event_borrarButtonActionPerformed

    private void posicionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionTextFieldActionPerformed
        // TODO add your handling code here:
        if (posicionTextField.getText().length() <= 2) {
            JOptionPane.showMessageDialog(this, "La posición de los helados ha de ser de dos numeros");
            reproducirSonidoAlerta();
        }
    }//GEN-LAST:event_posicionTextFieldActionPerformed

    private void dosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "2");
        }
    }//GEN-LAST:event_dosButtonActionPerformed

    private void sieteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "7");
        }
    }//GEN-LAST:event_sieteButtonActionPerformed

    private void tresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "3");
        }
    }//GEN-LAST:event_tresButtonActionPerformed

    private void seisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "6");
        }
    }//GEN-LAST:event_seisButtonActionPerformed

    private void nueveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveButtonActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        if (posicionTextField.getText().length() <= 1) {
            this.posicionTextField.setText(this.posicionTextField.getText() + "9");
        }
    }//GEN-LAST:event_nueveButtonActionPerformed

    private void dineroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_dineroTextFieldActionPerformed

    private void pedirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirButtonActionPerformed
        reproducirSonidoBoton();
        Helado conseguido = null;
        String pos = this.posicionTextField.getText();
        //DefaultTableModel m = (DefaultTableModel) this.heladosTable.getModel();
        //JOptionPane.showMessageDialog(this, "Aqui tienes tu " + m.getColumnName(3));
        try {
            // TODO add your handling code here:           
            conseguido = mh.pedirHelado(pos);
            //mh.setMonedero(mh.getMonedero());
            this.dineroTextField.setText(String.valueOf(mh.getMonedero()));
            reproducirSonidoCompra();
            JOptionPane.showMessageDialog(this, "Aquí tienes tu helado: " + conseguido.getNombre() + " , no se olvide del cambio " + mh.getMonedero() + " €");
            mh.setMonedero(0);
            this.dineroTextField.setText("0.00 €");
            refrescarTabla();
        } catch (Exception ex) {
            //Tipos de mensajes que se muestran
//            JOptionPane.showMessageDialog(null, "Este es un mensaje de advertencia", "Advertencia", JOptionPane.WARNING_MESSAGE);
//            JOptionPane.showMessageDialog(null, "Este es un mensaje de información", "Información", JOptionPane.INFORMATION_MESSAGE);
//            JOptionPane.showMessageDialog(null, "Este es un mensaje de error", "Error", JOptionPane.ERROR_MESSAGE);
//            JOptionPane.showMessageDialog(null, "Este es un mensaje simple", "Mensaje", JOptionPane.PLAIN_MESSAGE);
            reproducirSonidoAlerta();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_pedirButtonActionPerformed

    private void heladosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heladosTableMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = this.heladosTable.rowAtPoint(evt.getPoint());
        this.posicionTextField.setText(String.valueOf(this.heladosTable.getValueAt(filaSeleccionada, 0)));
    }//GEN-LAST:event_heladosTableMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        reproducirSonidoBoton();
        AuxVerVentas auxVerVentas = new AuxVerVentas(this, true);
        auxVerVentas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarButton;
    private javax.swing.JButton ceroButton;
    private javax.swing.JButton cincoButton;
    private javax.swing.JButton cuatroButton;
    private javax.swing.JTextField dineroTextField;
    private javax.swing.JButton dosButton;
    private javax.swing.JTable heladosTable;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nueveButton;
    private javax.swing.JButton ochoButton;
    private javax.swing.JButton pedirButton;
    private javax.swing.JTextField posicionTextField;
    private javax.swing.JButton seisButton;
    private javax.swing.JButton sieteButton;
    private javax.swing.JButton tresButton;
    private javax.swing.JButton unoButton;
    private javax.swing.JMenu verVentasMenu;
    // End of variables declaration//GEN-END:variables

}
